# Generated by Django 5.2.16 on 2026-07-18 03:17

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance_miles', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_duration_minutes', models.PositiveIntegerField()),
                ('leg_count', models.PositiveIntegerField()),
                ('stop_count', models.PositiveIntegerField()),
                ('duty_segment_count', models.PositiveIntegerField()),
                ('log_day_count', models.PositiveIntegerField()),
                ('departure_assumed', models.BooleanField(default=True)),
                ('result_snapshot', models.JSONField()),
            ],
        ),
    ]
